### ISSUE TITLE
Switch to RxJS 5

### ISSUE THREAD

**Issue by rgbkrk** [nteract/enchannel-zmq-backend#11]
The RxJS team is stellar and has convinced me we should just [switch on over to RxJS 5](http://stackoverflow.com/questions/34845778/create-an-rx-subject-using-subject-create-that-allows-onnext-without-subscriptio#comment57465887_34862286). @kenwheeler is going to switch [composition](https://github.com/nteract/composition) to RxJS 5 too.

We'll need to update the enchannel spec while we're at it for any interface changes.

/cc @blesh

**Comment by benlesh** [comment]
Cool. Let us know if you run into any issues.

**Comment by rgbkrk** [comment]
Only thing that caused me to misstep was the change to `Subject.create`, which I submitted a Doc PR for: https://github.com/ReactiveX/RxJS/pull/1241

The reason it took me a while to find this was my current three sources for docs:
- The migration guide
- http://reactivex.io/RxJS/ - which doesn't have Subject in it
- the code itself

I finally started digging around in making the `Observable` and `Observer`s directly until I finally figured out I was running into issues with `Subject.create`. We're using pretty vanilla operators here, so it wasn't a big deal.
