### ISSUE TITLE
add npm token for semantic release process as repo secret

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/enchannel-zmq-backend#63]

**Comment by captainsafia** [comment]
This is done now.

**Comment by alexandercbooth** [comment]
Thanks for adding @captainsafia! Looks like there was an issue with a mismatch of already published versions preventing a new release. I'll check into this tonight.

**Comment by alexandercbooth** [comment]
It seems like the issue was semantic-release getting the version from the git tags, which were behind the published version on npm. I apologize for pushing directly to master, but I just wanted to trigger the release once I updated the tags. A new version was released with that last commit and it looks like it's all set now.

**Comment by captainsafia** [comment]
@alexandercbooth No worries -- I actually just forgot that having the git tag was another requirement for this. Thanks for the follow-up.

**Comment by alexandercbooth** [comment]
@captainsafia No problem-- I'll tackle some of the others next 👍
